package sk.upjs.ics.minigolf.dataaccess;

import android.database.ContentObserver;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;

public interface Constants {
	String[] 						NO_PROJECTION = null;
	String[] 						ALL_COLUMNS = null;
	String 							NO_SELECTION = null;
	String[] 						NO_SELECTION_ARGS = null;
	String 							NO_SORT_ORDER = null;
	String 							NO_GROUP_BY = null;
	String 							NO_HAVING = null;
	String 							AUTOGENERATED_ID = null;
	SQLiteDatabase.CursorFactory 	DEFAULT_CURSOR_FACTORY = null;
	String 							NO_NULL_COLUMN_HACK = null;
	Cursor 							NO_CURSOR = null;
	ContentObserver 				NO_CONTENT_OBSERVER = null;
	Object 							NO_COOKIE = null;
	int 							NO_FLAGS = 0;
	int 							DEFAULT_LOADER_ID = 0;
	int								REQUEST_IMAGE_CAPTURE = 1;
}